apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantum-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quantum-microservice
  template:
    metadata:
      labels:
        app: quantum-microservice
    spec:
      containers:
      - name: quantum-microservice
        image: abhishekt/quantum-microservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8889
        env:
        - name: IBM_QUANTUM_TOKEN
          valueFrom:
            secretKeyRef:
              name: ibm-quantum-secret
              key: token
---
apiVersion: v1
kind: Service
metadata:
  name: quantum-microservice-service
spec:
  selector:
    app: quantum-microservice
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8889
      targetPort: 8889

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quantum-microservice-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: quantum-microservice-service
              port:
                number: 8889



